modLoader="javafml"
loaderVersion="[43,)"
license="AGPL-3.0"

[[mods]]
    modId="densemekanism"
    version="0.1.0"

    displayName="Dense Mekanism"
    authors="NewJumper"
    description='''Adds dense-ore variations for Mekanism ores for those lazy miners out there..'''

[[dependencies.densemekanism]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2, 1.20)"
    side="BOTH"

[[dependencies.densemekanism]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    side="BOTH"

[[dependencies.densemekanism]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.3.4,)"
    side="BOTH"
